/**
 * Generate glyph advances from what n8n actually renders.
 *
 * Two corrections are baked into this file, both found by measuring rather than
 * reasoning:
 *
 * 1. n8n draws in InterVariable, not the static Inter this repo bundles. Their
 *    advances differ materially -- a period is 0.220em against 0.288em -- so
 *    measuring our own font told us about our font, not about n8n.
 *
 * 2. InterVariable is optically sized, so advances are NOT proportional to font
 *    size. The same string measures 181.19px at 13px but 165.13px if measured at
 *    1000px and scaled down: small text is genuinely wider per em. Tables are
 *    therefore stored per size, in CSS pixels, and never normalised to an
 *    em square.
 *
 * The numbers were measured in a browser from a live n8n canvas (canvas
 * `measureText` at the exact size/weight the canvas draws) and are committed as
 * data in `packages/assets/data/<version>/font-metrics.json`; the file's own
 * `source` field records which n8n release was measured.
 *
 *   pnpm --filter workflow-render-core extract-font-metrics
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { EMULATED_VERSION } from 'workflow-render-assets';

const PKG = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const SOURCE = resolve(PKG, `../assets/data/${EMULATED_VERSION}/font-metrics.json`);

interface Measured {
  family: string;
  measuredAt: string;
  advances: Record<string, Record<string, number>>;
}

const measured = JSON.parse(readFileSync(SOURCE, 'utf8')) as Measured;

const tables: Record<string, Record<number, number>> = {};
const fallback: Record<string, number> = {};
for (const [key, table] of Object.entries(measured.advances)) {
  const numeric: Record<number, number> = {};
  for (const [cp, advance] of Object.entries(table)) numeric[Number(cp)] = advance;
  tables[key] = numeric;
  const values = Object.values(numeric);
  fallback[key] = values.reduce((sum, v) => sum + v, 0) / Math.max(values.length, 1);
}

const body = `/**
 * GENERATED by scripts/extract-font-metrics.mts — do not edit by hand.
 *
 * Glyph advances in CSS pixels, measured in a browser from a live n8n canvas
 * rendering ${measured.family} at each size and weight the canvas draws.
 * InterVariable is optically sized, so these are per size and are NOT
 * interchangeable between sizes by scaling.
 * Source: packages/assets/data/<version>/font-metrics.json (its \`source\`
 * field names the n8n release measured).
 */

/** Advance per codepoint, in px, keyed \`\${fontSize}/\${fontWeight}\`. */
export const ADVANCES: Record<string, Record<number, number>> = ${JSON.stringify(tables)};

/** Mean advance per table, used for a codepoint that was not measured. */
export const FALLBACK_ADVANCE: Record<string, number> = ${JSON.stringify(fallback)};

/** The size/weight pairs that were actually measured. */
export const MEASURED: { size: number; weight: number; key: string }[] = ${JSON.stringify(
  Object.keys(tables).map((key) => {
    const [size, weight] = key.split('/').map(Number);
    return { size: size ?? 0, weight: weight ?? 400, key };
  }),
)};
`;

writeFileSync(resolve(PKG, 'src/font-metrics.generated.ts'), body);
process.stdout.write(
  `wrote font metrics: ${Object.keys(tables).length} size/weight tables ` +
    `(${Object.keys(tables).join(', ')}), measured from ${measured.family}\n`,
);
